// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieReviews.Data;

#nullable disable

namespace MovieReviews.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924093554_AddNotes")]
    partial class AddNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BjTagPerformer", b =>
                {
                    b.Property<int>("BjTagsId")
                        .HasColumnType("int");

                    b.Property<int>("PerformersId")
                        .HasColumnType("int");

                    b.HasKey("BjTagsId", "PerformersId");

                    b.HasIndex("PerformersId");

                    b.ToTable("PerformerBjTags", (string)null);
                });

            modelBuilder.Entity("MovieReviews.Data.AssSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AssSize", (string)null);
                });

            modelBuilder.Entity("MovieReviews.Data.BjTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BjTag", (string)null);
                });

            modelBuilder.Entity("MovieReviews.Data.BoobSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoobSize", (string)null);
                });

            modelBuilder.Entity("MovieReviews.Data.GuideItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuideSectionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuideSectionId");

                    b.ToTable("GuideItems");
                });

            modelBuilder.Entity("MovieReviews.Data.GuideSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GuideSections");
                });

            modelBuilder.Entity("MovieReviews.Data.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("MovieReviews.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MovieReviews.Data.Performer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssSizeId")
                        .HasColumnType("int");

                    b.Property<int?>("BoobSizeId")
                        .HasColumnType("int");

                    b.Property<string>("BoobsQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsWatchlisted")
                        .HasColumnType("bit");

                    b.Property<string>("Moans")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SkinColorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssSizeId");

                    b.HasIndex("BoobSizeId");

                    b.HasIndex("SkinColorId");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("MovieReviews.Data.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPov")
                        .HasColumnType("bit");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OverallModifier")
                        .HasColumnType("int");

                    b.Property<int>("OverallRating")
                        .HasColumnType("int");

                    b.Property<string>("Positions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetupNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetupRating")
                        .HasColumnType("int");

                    b.Property<string>("SexNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SexRating")
                        .HasColumnType("int");

                    b.Property<string>("Studio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verdict")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("MovieReviews.Data.ScenePerformer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BjOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoobsOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoansOverride")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("SkinOverride")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("SceneId");

                    b.ToTable("ScenePerformers");
                });

            modelBuilder.Entity("MovieReviews.Data.SkinColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkinColor", (string)null);
                });

            modelBuilder.Entity("BjTagPerformer", b =>
                {
                    b.HasOne("MovieReviews.Data.BjTag", null)
                        .WithMany()
                        .HasForeignKey("BjTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReviews.Data.Performer", null)
                        .WithMany()
                        .HasForeignKey("PerformersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieReviews.Data.GuideItem", b =>
                {
                    b.HasOne("MovieReviews.Data.GuideSection", "Section")
                        .WithMany("Items")
                        .HasForeignKey("GuideSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("MovieReviews.Data.Performer", b =>
                {
                    b.HasOne("MovieReviews.Data.AssSize", "AssSize")
                        .WithMany("Performers")
                        .HasForeignKey("AssSizeId");

                    b.HasOne("MovieReviews.Data.BoobSize", "BoobSize")
                        .WithMany("Performers")
                        .HasForeignKey("BoobSizeId");

                    b.HasOne("MovieReviews.Data.SkinColor", "SkinColor")
                        .WithMany("Performers")
                        .HasForeignKey("SkinColorId");

                    b.Navigation("AssSize");

                    b.Navigation("BoobSize");

                    b.Navigation("SkinColor");
                });

            modelBuilder.Entity("MovieReviews.Data.ScenePerformer", b =>
                {
                    b.HasOne("MovieReviews.Data.Performer", "Performer")
                        .WithMany("Scenes")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieReviews.Data.Scene", "Scene")
                        .WithMany("Performers")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performer");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("MovieReviews.Data.AssSize", b =>
                {
                    b.Navigation("Performers");
                });

            modelBuilder.Entity("MovieReviews.Data.BoobSize", b =>
                {
                    b.Navigation("Performers");
                });

            modelBuilder.Entity("MovieReviews.Data.GuideSection", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MovieReviews.Data.Performer", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("MovieReviews.Data.Scene", b =>
                {
                    b.Navigation("Performers");
                });

            modelBuilder.Entity("MovieReviews.Data.SkinColor", b =>
                {
                    b.Navigation("Performers");
                });
#pragma warning restore 612, 618
        }
    }
}
